<?php

namespace Database\Seeders;

use App\Models\MGrupJamKerja;
use Illuminate\Database\Seeder;

class GrupJamKerjaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $grupJamKerja = [
            [
                'name' => 'Shift Pagi',
                'start' => '06:00',
                'end' => '14:00',
                'min_check_in' => '05:30',
                'max_check_in' => '06:30',
                'min_check_out' => '13:30',
                'max_check_out' => '14:30',
                'monday_start' => '06:00', 'monday_end' => '14:00', 'monday_min_check_in' => '05:30', 'monday_max_check_in' => '06:30', 'monday_min_check_out' => '13:30', 'monday_max_check_out' => '14:30', 'monday_type' => 'WEEKDAY',
                'tuesday_start' => '06:00', 'tuesday_end' => '14:00', 'tuesday_min_check_in' => '05:30', 'tuesday_max_check_in' => '06:30', 'tuesday_min_check_out' => '13:30', 'tuesday_max_check_out' => '14:30', 'tuesday_type' => 'WEEKDAY',
                'wednesday_start' => '06:00', 'wednesday_end' => '14:00', 'wednesday_min_check_in' => '05:30', 'wednesday_max_check_in' => '06:30', 'wednesday_min_check_out' => '13:30', 'wednesday_max_check_out' => '14:30', 'wednesday_type' => 'WEEKDAY',
                'thursday_start' => '06:00', 'thursday_end' => '14:00', 'thursday_min_check_in' => '05:30', 'thursday_max_check_in' => '06:30', 'thursday_min_check_out' => '13:30', 'thursday_max_check_out' => '14:30', 'thursday_type' => 'WEEKDAY',
                'friday_start' => '06:00', 'friday_end' => '14:00', 'friday_min_check_in' => '05:30', 'friday_max_check_in' => '06:30', 'friday_min_check_out' => '13:30', 'friday_max_check_out' => '14:30', 'friday_type' => 'WEEKDAY',
                'saturday_start' => null, 'saturday_end' => null, 'saturday_min_check_in' => null, 'saturday_max_check_in' => null, 'saturday_min_check_out' => null, 'saturday_max_check_out' => null, 'saturday_type' => 'OFF',
                'sunday_start' => null, 'sunday_end' => null, 'sunday_min_check_in' => null, 'sunday_max_check_in' => null, 'sunday_min_check_out' => null, 'sunday_max_check_out' => null, 'sunday_type' => 'OFF',
            ],
            [
                'name' => 'Shift Siang',
                'start' => '14:00',
                'end' => '22:00',
                'min_check_in' => '13:30',
                'max_check_in' => '14:30',
                'min_check_out' => '21:30',
                'max_check_out' => '22:30',
                'monday_start' => '14:00', 'monday_end' => '22:00', 'monday_min_check_in' => '13:30', 'monday_max_check_in' => '14:30', 'monday_min_check_out' => '21:30', 'monday_max_check_out' => '22:30', 'monday_type' => 'WEEKDAY',
                'tuesday_start' => '14:00', 'tuesday_end' => '22:00', 'tuesday_min_check_in' => '13:30', 'tuesday_max_check_in' => '14:30', 'tuesday_min_check_out' => '21:30', 'tuesday_max_check_out' => '22:30', 'tuesday_type' => 'WEEKDAY',
                'wednesday_start' => '14:00', 'wednesday_end' => '22:00', 'wednesday_min_check_in' => '13:30', 'wednesday_max_check_in' => '14:30', 'wednesday_min_check_out' => '21:30', 'wednesday_max_check_out' => '22:30', 'wednesday_type' => 'WEEKDAY',
                'thursday_start' => '14:00', 'thursday_end' => '22:00', 'thursday_min_check_in' => '13:30', 'thursday_max_check_in' => '14:30', 'thursday_min_check_out' => '21:30', 'thursday_max_check_out' => '22:30', 'thursday_type' => 'WEEKDAY',
                'friday_start' => '14:00', 'friday_end' => '22:00', 'friday_min_check_in' => '13:30', 'friday_max_check_in' => '14:30', 'friday_min_check_out' => '21:30', 'friday_max_check_out' => '22:30', 'friday_type' => 'WEEKDAY',
                'saturday_start' => null, 'saturday_end' => null, 'saturday_min_check_in' => null, 'saturday_max_check_in' => null, 'saturday_min_check_out' => null, 'saturday_max_check_out' => null, 'saturday_type' => 'OFF',
                'sunday_start' => null, 'sunday_end' => null, 'sunday_min_check_in' => null, 'sunday_max_check_in' => null, 'sunday_min_check_out' => null, 'sunday_max_check_out' => null, 'sunday_type' => 'OFF',
            ],
            [
                'name' => 'Shift Malam',
                'start' => '22:00',
                'end' => '06:00',
                'min_check_in' => '21:30',
                'max_check_in' => '22:30',
                'min_check_out' => '05:30',
                'max_check_out' => '06:30',
                'monday_start' => '22:00', 'monday_end' => '06:00', 'monday_min_check_in' => '21:30', 'monday_max_check_in' => '22:30', 'monday_min_check_out' => '05:30', 'monday_max_check_out' => '06:30', 'monday_type' => 'WEEKDAY',
                'tuesday_start' => '22:00', 'tuesday_end' => '06:00', 'tuesday_min_check_in' => '21:30', 'tuesday_max_check_in' => '22:30', 'tuesday_min_check_out' => '05:30', 'tuesday_max_check_out' => '06:30', 'tuesday_type' => 'WEEKDAY',
                'wednesday_start' => '22:00', 'wednesday_end' => '06:00', 'wednesday_min_check_in' => '21:30', 'wednesday_max_check_in' => '22:30', 'wednesday_min_check_out' => '05:30', 'wednesday_max_check_out' => '06:30', 'wednesday_type' => 'WEEKDAY',
                'thursday_start' => '22:00', 'thursday_end' => '06:00', 'thursday_min_check_in' => '21:30', 'thursday_max_check_in' => '22:30', 'thursday_min_check_out' => '05:30', 'thursday_max_check_out' => '06:30', 'thursday_type' => 'WEEKDAY',
                'friday_start' => '22:00', 'friday_end' => '06:00', 'friday_min_check_in' => '21:30', 'friday_max_check_in' => '22:30', 'friday_min_check_out' => '05:30', 'friday_max_check_out' => '06:30', 'friday_type' => 'WEEKDAY',
                'saturday_start' => null, 'saturday_end' => null, 'saturday_min_check_in' => null, 'saturday_max_check_in' => null, 'saturday_min_check_out' => null, 'saturday_max_check_out' => null, 'saturday_type' => 'OFF',
                'sunday_start' => null, 'sunday_end' => null, 'sunday_min_check_in' => null, 'sunday_max_check_in' => null, 'sunday_min_check_out' => null, 'sunday_max_check_out' => null, 'sunday_type' => 'OFF',
            ],
            [
                'name' => 'Jam Kantor Regular',
                'start' => '08:00',
                'end' => '17:00',
                'min_check_in' => '07:30',
                'max_check_in' => '08:30',
                'min_check_out' => '16:30',
                'max_check_out' => '17:30',
                'monday_start' => '08:00', 'monday_end' => '17:00', 'monday_min_check_in' => '07:30', 'monday_max_check_in' => '08:30', 'monday_min_check_out' => '16:30', 'monday_max_check_out' => '17:30', 'monday_type' => 'WEEKDAY',
                'tuesday_start' => '08:00', 'tuesday_end' => '17:00', 'tuesday_min_check_in' => '07:30', 'tuesday_max_check_in' => '08:30', 'tuesday_min_check_out' => '16:30', 'tuesday_max_check_out' => '17:30', 'tuesday_type' => 'WEEKDAY',
                'wednesday_start' => '08:00', 'wednesday_end' => '17:00', 'wednesday_min_check_in' => '07:30', 'wednesday_max_check_in' => '08:30', 'wednesday_min_check_out' => '16:30', 'wednesday_max_check_out' => '17:30', 'wednesday_type' => 'WEEKDAY',
                'thursday_start' => '08:00', 'thursday_end' => '17:00', 'thursday_min_check_in' => '07:30', 'thursday_max_check_in' => '08:30', 'thursday_min_check_out' => '16:30', 'thursday_max_check_out' => '17:30', 'thursday_type' => 'WEEKDAY',
                'friday_start' => '08:00', 'friday_end' => '17:00', 'friday_min_check_in' => '07:30', 'friday_max_check_in' => '08:30', 'friday_min_check_out' => '16:30', 'friday_max_check_out' => '17:30', 'friday_type' => 'WEEKDAY',
                'saturday_start' => null, 'saturday_end' => null, 'saturday_min_check_in' => null, 'saturday_max_check_in' => null, 'saturday_min_check_out' => null, 'saturday_max_check_out' => null, 'saturday_type' => 'OFF',
                'sunday_start' => null, 'sunday_end' => null, 'sunday_min_check_in' => null, 'sunday_max_check_in' => null, 'sunday_min_check_out' => null, 'sunday_max_check_out' => null, 'sunday_type' => 'OFF',
            ],
            [
                'name' => 'Jam Kantor Fleksibel',
                'start' => '09:00',
                'end' => '18:00',
                'min_check_in' => '07:00',
                'max_check_in' => '10:00',
                'min_check_out' => '17:00',
                'max_check_out' => '20:00',
                'monday_start' => '09:00', 'monday_end' => '18:00', 'monday_min_check_in' => '07:00', 'monday_max_check_in' => '10:00', 'monday_min_check_out' => '17:00', 'monday_max_check_out' => '20:00', 'monday_type' => 'WEEKDAY',
                'tuesday_start' => '09:00', 'tuesday_end' => '18:00', 'tuesday_min_check_in' => '07:00', 'tuesday_max_check_in' => '10:00', 'tuesday_min_check_out' => '17:00', 'tuesday_max_check_out' => '20:00', 'tuesday_type' => 'WEEKDAY',
                'wednesday_start' => '09:00', 'wednesday_end' => '18:00', 'wednesday_min_check_in' => '07:00', 'wednesday_max_check_in' => '10:00', 'wednesday_min_check_out' => '17:00', 'wednesday_max_check_out' => '20:00', 'wednesday_type' => 'WEEKDAY',
                'thursday_start' => '09:00', 'thursday_end' => '18:00', 'thursday_min_check_in' => '07:00', 'thursday_max_check_in' => '10:00', 'thursday_min_check_out' => '17:00', 'thursday_max_check_out' => '20:00', 'thursday_type' => 'WEEKDAY',
                'friday_start' => '09:00', 'friday_end' => '18:00', 'friday_min_check_in' => '07:00', 'friday_max_check_in' => '10:00', 'friday_min_check_out' => '17:00', 'friday_max_check_out' => '20:00', 'friday_type' => 'WEEKDAY',
                'saturday_start' => null, 'saturday_end' => null, 'saturday_min_check_in' => null, 'saturday_max_check_in' => null, 'saturday_min_check_out' => null, 'saturday_max_check_out' => null, 'saturday_type' => 'OFF',
                'sunday_start' => null, 'sunday_end' => null, 'sunday_min_check_in' => null, 'sunday_max_check_in' => null, 'sunday_min_check_out' => null, 'sunday_max_check_out' => null, 'sunday_type' => 'OFF',
            ],
            [
                'name' => 'Full 24 Jam',
                'start' => '00:00',
                'end' => '23:59',
                'min_check_in' => '00:00',
                'max_check_in' => '23:59',
                'min_check_out' => '00:00',
                'max_check_out' => '23:59',
                'monday_start' => '00:00', 'monday_end' => '23:59', 'monday_min_check_in' => '00:00', 'monday_max_check_in' => '23:59', 'monday_min_check_out' => '00:00', 'monday_max_check_out' => '23:59', 'monday_type' => 'FULL',
                'tuesday_start' => '00:00', 'tuesday_end' => '23:59', 'tuesday_min_check_in' => '00:00', 'tuesday_max_check_in' => '23:59', 'tuesday_min_check_out' => '00:00', 'tuesday_max_check_out' => '23:59', 'tuesday_type' => 'FULL',
                'wednesday_start' => '00:00', 'wednesday_end' => '23:59', 'wednesday_min_check_in' => '00:00', 'wednesday_max_check_in' => '23:59', 'wednesday_min_check_out' => '00:00', 'wednesday_max_check_out' => '23:59', 'wednesday_type' => 'FULL',
                'thursday_start' => '00:00', 'thursday_end' => '23:59', 'thursday_min_check_in' => '00:00', 'thursday_max_check_in' => '23:59', 'thursday_min_check_out' => '00:00', 'thursday_max_check_out' => '23:59', 'thursday_type' => 'FULL',
                'friday_start' => '00:00', 'friday_end' => '23:59', 'friday_min_check_in' => '00:00', 'friday_max_check_in' => '23:59', 'friday_min_check_out' => '00:00', 'friday_max_check_out' => '23:59', 'friday_type' => 'FULL',
                'saturday_start' => '00:00', 'saturday_end' => '23:59', 'saturday_min_check_in' => '00:00', 'saturday_max_check_in' => '23:59', 'saturday_min_check_out' => '00:00', 'saturday_max_check_out' => '23:59', 'saturday_type' => 'FULL',
                'sunday_start' => '00:00', 'sunday_end' => '23:59', 'sunday_min_check_in' => '00:00', 'sunday_max_check_in' => '23:59', 'sunday_min_check_out' => '00:00', 'sunday_max_check_out' => '23:59', 'sunday_type' => 'FULL',
            ],
            [
                'name' => 'Shift Retail',
                'start' => '10:00',
                'end' => '22:00',
                'min_check_in' => '09:30',
                'max_check_in' => '10:30',
                'min_check_out' => '21:30',
                'max_check_out' => '22:30',
                'monday_start' => '10:00', 'monday_end' => '22:00', 'monday_min_check_in' => '09:30', 'monday_max_check_in' => '10:30', 'monday_min_check_out' => '21:30', 'monday_max_check_out' => '22:30', 'monday_type' => 'WEEKDAY',
                'tuesday_start' => '10:00', 'tuesday_end' => '22:00', 'tuesday_min_check_in' => '09:30', 'tuesday_max_check_in' => '10:30', 'tuesday_min_check_out' => '21:30', 'tuesday_max_check_out' => '22:30', 'tuesday_type' => 'WEEKDAY',
                'wednesday_start' => '10:00', 'wednesday_end' => '22:00', 'wednesday_min_check_in' => '09:30', 'wednesday_max_check_in' => '10:30', 'wednesday_min_check_out' => '21:30', 'wednesday_max_check_out' => '22:30', 'wednesday_type' => 'WEEKDAY',
                'thursday_start' => '10:00', 'thursday_end' => '22:00', 'thursday_min_check_in' => '09:30', 'thursday_max_check_in' => '10:30', 'thursday_min_check_out' => '21:30', 'thursday_max_check_out' => '22:30', 'thursday_type' => 'WEEKDAY',
                'friday_start' => '10:00', 'friday_end' => '22:00', 'friday_min_check_in' => '09:30', 'friday_max_check_in' => '10:30', 'friday_min_check_out' => '21:30', 'friday_max_check_out' => '22:30', 'friday_type' => 'WEEKDAY',
                'saturday_start' => '10:00', 'saturday_end' => '22:00', 'saturday_min_check_in' => '09:30', 'saturday_max_check_in' => '10:30', 'saturday_min_check_out' => '21:30', 'saturday_max_check_out' => '22:30', 'saturday_type' => 'WEEKEND',
                'sunday_start' => '10:00', 'sunday_end' => '22:00', 'sunday_min_check_in' => '09:30', 'sunday_max_check_in' => '10:30', 'sunday_min_check_out' => '21:30', 'sunday_max_check_out' => '22:30', 'sunday_type' => 'WEEKEND',
            ],
            [
                'name' => 'Part Time Pagi',
                'start' => '08:00',
                'end' => '12:00',
                'min_check_in' => '07:30',
                'max_check_in' => '08:30',
                'min_check_out' => '11:30',
                'max_check_out' => '12:30',
                'monday_start' => '08:00', 'monday_end' => '12:00', 'monday_min_check_in' => '07:30', 'monday_max_check_in' => '08:30', 'monday_min_check_out' => '11:30', 'monday_max_check_out' => '12:30', 'monday_type' => 'WEEKDAY',
                'tuesday_start' => '08:00', 'tuesday_end' => '12:00', 'tuesday_min_check_in' => '07:30', 'tuesday_max_check_in' => '08:30', 'tuesday_min_check_out' => '11:30', 'tuesday_max_check_out' => '12:30', 'tuesday_type' => 'WEEKDAY',
                'wednesday_start' => '08:00', 'wednesday_end' => '12:00', 'wednesday_min_check_in' => '07:30', 'wednesday_max_check_in' => '08:30', 'wednesday_min_check_out' => '11:30', 'wednesday_max_check_out' => '12:30', 'wednesday_type' => 'WEEKDAY',
                'thursday_start' => '08:00', 'thursday_end' => '12:00', 'thursday_min_check_in' => '07:30', 'thursday_max_check_in' => '08:30', 'thursday_min_check_out' => '11:30', 'thursday_max_check_out' => '12:30', 'thursday_type' => 'WEEKDAY',
                'friday_start' => '08:00', 'friday_end' => '12:00', 'friday_min_check_in' => '07:30', 'friday_max_check_in' => '08:30', 'friday_min_check_out' => '11:30', 'friday_max_check_out' => '12:30', 'friday_type' => 'WEEKDAY',
                'saturday_start' => null, 'saturday_end' => null, 'saturday_min_check_in' => null, 'saturday_max_check_in' => null, 'saturday_min_check_out' => null, 'saturday_max_check_out' => null, 'saturday_type' => 'OFF',
                'sunday_start' => null, 'sunday_end' => null, 'sunday_min_check_in' => null, 'sunday_max_check_in' => null, 'sunday_min_check_out' => null, 'sunday_max_check_out' => null, 'sunday_type' => 'OFF',
            ],
            [
                'name' => 'Part Time Sore',
                'start' => '13:00',
                'end' => '17:00',
                'min_check_in' => '12:30',
                'max_check_in' => '13:30',
                'min_check_out' => '16:30',
                'max_check_out' => '17:30',
                'monday_start' => '13:00', 'monday_end' => '17:00', 'monday_min_check_in' => '12:30', 'monday_max_check_in' => '13:30', 'monday_min_check_out' => '16:30', 'monday_max_check_out' => '17:30', 'monday_type' => 'WEEKDAY',
                'tuesday_start' => '13:00', 'tuesday_end' => '17:00', 'tuesday_min_check_in' => '12:30', 'tuesday_max_check_in' => '13:30', 'tuesday_min_check_out' => '16:30', 'tuesday_max_check_out' => '17:30', 'tuesday_type' => 'WEEKDAY',
                'wednesday_start' => '13:00', 'wednesday_end' => '17:00', 'wednesday_min_check_in' => '12:30', 'wednesday_max_check_in' => '13:30', 'wednesday_min_check_out' => '16:30', 'wednesday_max_check_out' => '17:30', 'wednesday_type' => 'WEEKDAY',
                'thursday_start' => '13:00', 'thursday_end' => '17:00', 'thursday_min_check_in' => '12:30', 'thursday_max_check_in' => '13:30', 'thursday_min_check_out' => '16:30', 'thursday_max_check_out' => '17:30', 'thursday_type' => 'WEEKDAY',
                'friday_start' => '13:00', 'friday_end' => '17:00', 'friday_min_check_in' => '12:30', 'friday_max_check_in' => '13:30', 'friday_min_check_out' => '16:30', 'friday_max_check_out' => '17:30', 'friday_type' => 'WEEKDAY',
                'saturday_start' => null, 'saturday_end' => null, 'saturday_min_check_in' => null, 'saturday_max_check_in' => null, 'saturday_min_check_out' => null, 'saturday_max_check_out' => null, 'saturday_type' => 'OFF',
                'sunday_start' => null, 'sunday_end' => null, 'sunday_min_check_in' => null, 'sunday_max_check_in' => null, 'sunday_min_check_out' => null, 'sunday_max_check_out' => null, 'sunday_type' => 'OFF',
            ],
            [
                'name' => 'Satpam 12 Jam',
                'start' => '07:00',
                'end' => '19:00',
                'min_check_in' => '06:30',
                'max_check_in' => '07:30',
                'min_check_out' => '18:30',
                'max_check_out' => '19:30',
                'monday_start' => '07:00', 'monday_end' => '19:00', 'monday_min_check_in' => '06:30', 'monday_max_check_in' => '07:30', 'monday_min_check_out' => '18:30', 'monday_max_check_out' => '19:30', 'monday_type' => 'WEEKDAY',
                'tuesday_start' => '07:00', 'tuesday_end' => '19:00', 'tuesday_min_check_in' => '06:30', 'tuesday_max_check_in' => '07:30', 'tuesday_min_check_out' => '18:30', 'tuesday_max_check_out' => '19:30', 'tuesday_type' => 'WEEKDAY',
                'wednesday_start' => '07:00', 'wednesday_end' => '19:00', 'wednesday_min_check_in' => '06:30', 'wednesday_max_check_in' => '07:30', 'wednesday_min_check_out' => '18:30', 'wednesday_max_check_out' => '19:30', 'wednesday_type' => 'WEEKDAY',
                'thursday_start' => '07:00', 'thursday_end' => '19:00', 'thursday_min_check_in' => '06:30', 'thursday_max_check_in' => '07:30', 'thursday_min_check_out' => '18:30', 'thursday_max_check_out' => '19:30', 'thursday_type' => 'WEEKDAY',
                'friday_start' => '07:00', 'friday_end' => '19:00', 'friday_min_check_in' => '06:30', 'friday_max_check_in' => '07:30', 'friday_min_check_out' => '18:30', 'friday_max_check_out' => '19:30', 'friday_type' => 'WEEKDAY',
                'saturday_start' => '07:00', 'saturday_end' => '19:00', 'saturday_min_check_in' => '06:30', 'saturday_max_check_in' => '07:30', 'saturday_min_check_out' => '18:30', 'saturday_max_check_out' => '19:30', 'saturday_type' => 'WEEKEND',
                'sunday_start' => '07:00', 'sunday_end' => '19:00', 'sunday_min_check_in' => '06:30', 'sunday_max_check_in' => '07:30', 'sunday_min_check_out' => '18:30', 'sunday_max_check_out' => '19:30', 'sunday_type' => 'WEEKEND',
            ],
        ];

        foreach ($grupJamKerja as $data) {
            MGrupJamKerja::create($data);
        }
    }
}
